import type { Analytics, BloodRequest, Donor, DonorMatch } from "./humapulse-types";

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString();
const hoursAhead = (h: number) => new Date(now + h * 3600_000).toISOString();

export const demoRequests: BloodRequest[] = [
  {
    id: "REQ-10241",
    requester_id: "USR-8831",
    hospital_name: "Aga Khan University Hospital",
    city: "Karachi",
    blood_group: "O-",
    units_required: 3,
    units_arranged: 1,
    urgency: "critical",
    status: "active",
    required_before: hoursAhead(5),
    created_at: hoursAgo(1),
    notes: "Trauma patient in ICU, continuous transfusion required.",
  },
  {
    id: "REQ-10238",
    requester_id: "USR-7412",
    hospital_name: "Shaukat Khanum Memorial",
    city: "Lahore",
    blood_group: "A+",
    units_required: 2,
    units_arranged: 2,
    urgency: "urgent",
    status: "active",
    required_before: hoursAhead(18),
    created_at: hoursAgo(4),
    notes: "Scheduled chemotherapy support.",
  },
  {
    id: "REQ-10233",
    requester_id: "USR-5566",
    hospital_name: "Pakistan Institute of Medical Sciences",
    city: "Islamabad",
    blood_group: "B+",
    units_required: 4,
    units_arranged: 1,
    urgency: "critical",
    status: "active",
    required_before: hoursAhead(9),
    created_at: hoursAgo(7),
    notes: "Postpartum hemorrhage, maternity ward.",
  },
  {
    id: "REQ-10229",
    requester_id: "USR-3120",
    hospital_name: "Civil Hospital",
    city: "Hyderabad",
    blood_group: "AB-",
    units_required: 1,
    units_arranged: 0,
    urgency: "normal",
    status: "active",
    required_before: hoursAhead(60),
    created_at: hoursAgo(20),
    notes: "Elective surgery backup unit.",
  },
  {
    id: "REQ-10217",
    requester_id: "USR-9044",
    hospital_name: "Services Hospital",
    city: "Lahore",
    blood_group: "O+",
    units_required: 2,
    units_arranged: 2,
    urgency: "urgent",
    status: "fulfilled",
    required_before: hoursAgo(6),
    created_at: hoursAgo(30),
    notes: "Road accident, units arranged by two verified donors.",
  },
  {
    id: "REQ-10205",
    requester_id: "USR-2277",
    hospital_name: "Lady Reading Hospital",
    city: "Peshawar",
    blood_group: "B-",
    units_required: 2,
    units_arranged: 0,
    urgency: "normal",
    status: "cancelled",
    required_before: hoursAgo(12),
    created_at: hoursAgo(48),
    notes: "Patient transferred to another facility.",
  },
];

export const demoMatches: DonorMatch[] = [
  {
    donor_id: "DNR-4471",
    masked_name: "A**** K****",
    blood_group: "O-",
    match_score: 94,
    distance_km: 2.1,
    eligible: true,
    last_donation: hoursAgo(24 * 120),
    city: "Karachi",
  },
  {
    donor_id: "DNR-3318",
    masked_name: "S**** R****",
    blood_group: "O-",
    match_score: 88.5,
    distance_km: 4.6,
    eligible: true,
    last_donation: hoursAgo(24 * 190),
    city: "Karachi",
  },
  {
    donor_id: "DNR-2890",
    masked_name: "M**** H****",
    blood_group: "O-",
    match_score: 81.2,
    distance_km: 7.9,
    eligible: true,
    last_donation: hoursAgo(24 * 95),
    city: "Karachi",
  },
  {
    donor_id: "DNR-1204",
    masked_name: "F**** N****",
    blood_group: "O-",
    match_score: 66.4,
    distance_km: 13.2,
    eligible: false,
    last_donation: hoursAgo(24 * 30),
    city: "Karachi",
  },
];

export const demoDonors: Donor[] = [
  { id: "DNR-4471", masked_name: "A**** K****", blood_group: "O-", city: "Karachi", available: true, verified: true, total_donations: 11, last_donation: hoursAgo(24 * 120) },
  { id: "DNR-3318", masked_name: "S**** R****", blood_group: "O-", city: "Karachi", available: true, verified: true, total_donations: 7, last_donation: hoursAgo(24 * 190) },
  { id: "DNR-5521", masked_name: "H**** B****", blood_group: "A+", city: "Lahore", available: true, verified: true, total_donations: 4, last_donation: hoursAgo(24 * 140) },
  { id: "DNR-6610", masked_name: "Z**** A****", blood_group: "B+", city: "Islamabad", available: false, verified: true, total_donations: 9, last_donation: hoursAgo(24 * 20) },
  { id: "DNR-7733", masked_name: "N**** S****", blood_group: "AB-", city: "Hyderabad", available: true, verified: false, total_donations: 1 },
  { id: "DNR-8812", masked_name: "I**** Q****", blood_group: "O+", city: "Lahore", available: true, verified: true, total_donations: 15, last_donation: hoursAgo(24 * 210) },
  { id: "DNR-9031", masked_name: "R**** T****", blood_group: "A-", city: "Peshawar", available: false, verified: true, total_donations: 3, last_donation: hoursAgo(24 * 44) },
  { id: "DNR-9902", masked_name: "K**** M****", blood_group: "AB+", city: "Karachi", available: true, verified: true, total_donations: 6, last_donation: hoursAgo(24 * 160) },
];

export const demoAnalytics: Analytics = {
  total_requests: 1284,
  active_emergency_requests: 37,
  completed_donations: 946,
  registered_donors: 4218,
  available_donors: 2871,
  fulfillment_rate: 73.6,
  demand_by_blood_group: [
    { blood_group: "O+", requests: 318 },
    { blood_group: "O-", requests: 211 },
    { blood_group: "A+", requests: 243 },
    { blood_group: "A-", requests: 96 },
    { blood_group: "B+", requests: 187 },
    { blood_group: "B-", requests: 74 },
    { blood_group: "AB+", requests: 89 },
    { blood_group: "AB-", requests: 66 },
  ],
  requests_by_urgency: [
    { urgency: "Normal", count: 512 },
    { urgency: "Urgent", count: 489 },
    { urgency: "Critical", count: 283 },
  ],
};
